config/routes.rb
Scrum::Application.routes.draw do
  resources :users
  resources :tasks do
    member do
      get "join"
      get "kick"
      get "trequests"
      match "/accept/:trequest_id", to: "tasks#accept"
      match "/decline/:trequest_id", to: "tasks#decline"
    end
    collection do
      get 'browse'
      get "addtask"
    end
  end
  resources :projects do
    member do
      get "join"
      get "kick"
      get "prequests"
      match "/accept/:prequest_id", to: "projects#accept"
      match "/decline/:prequest_id", to: "projects#decline"
    end
    collection do
      get 'browse'
      get "addtask"
    end
  end

  resources :groups do
    member do
      get "join"
      get "kick"
      get "grequests"
      match "/accept/:grequest_id", to: "groups#accept"
      match "/decline/:grequest_id", to: "groups#decline"
    end
    collection do
      get 'browse'
    end
  end
  resources :sessions, only: :create

  match "/",          to: "application#home", :as => :home
  match "/signup",    to: "users#new"
  match "/signin",    to: "sessions#new"
  match "/signout",    to: "sessions#destroy"

  

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :parent_id, :project_id, :group_id
  belongs_to :project
  # Parent id is id of parent TASK
  has_many :tasks, :foreign_key => "parent_id"
  belongs_to :task
  has_and_belongs_to_many :users
  has_and_belongs_to_many :languages
  has_many :trequests
  belongs_to :group
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @user = current_user
    @task = Task.new
  end
  def create
    @task = Task.new(params[:task])
    @task.users << current_user
    @task.group_id = @task.project.group.id
    
    if @task.save
      redirect_to task_path(@task)
    else
      render 'new'
    end
  end
  def index
    @tasks = current_user.tasks
  end
  def browse
    @tasks = []
    @projects = current_user.projects
    @projects.each do |p|
      p.tasks.each do |t|
        if !@tasks.include? t
          @tasks.push t
        end
      end
    end
    render 'index'
  end
  def show
    @task = Task.find(params[:id])
    @users = @task.users
  end
  def destroy
    @task = Task.find(params[:id])
    @task.tasks.each do |t|
      t.destroy
    end
    puts "-------------------------"
    puts "Destroying Task"
    puts @task.destroy
    puts "-------------------------"
    redirect_to "/tasks"
  end
  def kick
    @user = User.find(params[:user_id])
    @task = Task.find(params[:id])
    #Add code to remove from all tasks and subtasks too
    if @task.users.include? @user
      @task.users.delete(@user)
    end
  end
  def join
    @task = Task.find(params[:id])
    @trequests = @task.trequests.where("user_id = ?", current_user.id)
    if @task and current_user.projects.include? @task.project
      if !@trequests.any?
        @trequest = Trequest.new(user_id: current_user.id,
                            task_id: @task.id)
        if @trequest.save
          redirect_to task_path(@task)
        else
          flash["error"] = "Could not create a request"
          redirect_to request.referer
        end
      else
        flash["error"] = "You have already requested to join"
        redirect_to request.referer
      end
    else
      flash["error"] = "Not a valid task"
      redirect_to request.referer
    end
  end
  def accept
    @trequest = Trequest.find(params[:trequest_id])
    @trequest.task.users << @trequest.user
    @trequest.delete
    redirect_to request.referer
  end
  def decline
    @trequest = Trequest.find(params[:trequest_id])
    @trequest.delete
    redirect_to request.referer
  end
end

app/views/tasks/_new.html.erb
<div id="newTaskModal" class="accordion-body collapse">
  <div class="accordion-inner">
    <textarea id="new-task-description"></textarea><br>
    <button onclick="submitTask(<%= @project.id %>)" class="btn btn-success">Add Task</button>
  </div>
</div>

app/views/tasks/_task.html.erb
<link rel="stylesheet" type="text/css" href="/assets/partials.css">
<div class="partial">
  <a href="/tasks/<%= task.id %>" class="hidden-link">
    <div>
      <%= task.description %>
    </div>
    <% if task.users.include? current_user %>
      <%= button_to "Delete",task, method: "delete", class: "btn btn-danger" %>
    <% end %>
    <% if current_user.projects.include? task.project and !task.users.include? current_user %>
      <%= link_to "Join", join_task_path(task) , class: "btn" %>
    <% end %>
    <br>
  </a>
</div>

app/views/tasks/index.html.erb
<%= render @tasks %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |t| %>
  <%= t.text_area :description, :placeholder => "Summarize the task", class: "description" %>
  <br>
  <%= t.collection_select(:project_id, @hprojects, :id, :name) %>
  <%= t.submit "Create Task", class: "btn btn-primary" %>
<% end %>

app/views/tasks/show.html.erb
<span class="alignright">
<h5>Group</h5>
<%= render @task.group %>

<% if current_user.projects.include? @task.project and !@task.users.include? current_user %>
  <% if Trequest.find_by_user_id_and_task_id(current_user.id, @task.id) %>
    <%= link_to '#', class: "btn disabled btn-warning" do %>
      <i class="icon-exclamation-sign icon-white"></i>
      Requested
    <% end %>
  <% else %>
    <%= link_to 'Join', task_join_path(@task), class: "btn btn-primary" %>
  <% end %>
<% else %>
  <%= link_to '#', class: "btn disabled btn-success" do %>
    <i class="icon-ok icon-white"></i>
    Member
  <% end %>
<% end %>

<% if @task.users.include? current_user %>
  <%= button_to "Delete",@task, method: "delete", class: "btn btn-danger" %>
<% end %>
</span>
    <i class="icon-ok icon-white"></i>

<h5>Task Description</h5>
<%= @task.description %>
<br><br><br>
<div class="tabbable">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#task-tab" data-toggle="tab">Sub Tasks</a></li>
    <li ><a href="#feed-tab" data-toggle="tab">Feed</a></li>
    <li><a href="#member-tab" data-toggle="tab"> Users</a></li>
    <% if @task.users.include? current_user %>
      <li ><a href="#join-tab" data-toggle="tab">Requests to Join</a></li>
    <% end %>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="task-tab">
      <%= render @task.tasks %>
    </div>
    <div class="tab-pane" id="feed-tab">
    </div>
    <div class="tab-pane" id="member-tab">
      <%= render @task.users %>
    </div>
    <div class="tab-pane" id="join-tab">
         <%= render @task.trequests %>  
    </div>
  </div>
</div>