config/routes.rb
Scrum::Application.routes.draw do
  resources :users
  resources :tasks do
    member do
      get "join"
      get "kick"
      get "trequests"
      match "/accept/:trequest_id", to: "tasks#accept"
      match "/decline/:trequest_id", to: "tasks#decline"
    end
    collection do
      get 'browse'
      get "addtask"
    end
  end
  resources :projects do
    member do
      get "join"
      get "kick"
      get "prequests"
      match "/accept/:prequest_id", to: "projects#accept"
      match "/decline/:prequest_id", to: "projects#decline"
    end
    collection do
      get 'browse'
      get "addtask"
    end
  end

  resources :groups do
    member do
      get "join"
      get "kick"
      get "grequests"
      match "/accept/:grequest_id", to: "groups#accept"
      match "/decline/:grequest_id", to: "groups#decline"
    end
    collection do
      get 'browse'
    end
  end
  resources :sessions, only: :create

  match "/",          to: "application#home", :as => :home
  match "/signup",    to: "users#new"
  match "/signin",    to: "sessions#new"
  match "/signout",    to: "sessions#destroy"

  

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :name
  has_many :projects
  has_and_belongs_to_many :mods, :class_name => 'User', :join_table => :groups_mods
  has_and_belongs_to_many :members, :class_name => 'User', :join_table => :groups_members
  has_many :grequests

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end
  def show
    @group = Group.find(params[:id])
  end
  def create
    @group = Group.new params[:group]
    if @group.save
      @group.members << current_user
      @group.mods << current_user
      redirect_to "/groups"
    else
      render 'new'
    end
  end
  def index
    @groups = current_user.groups
  end
  def browse
    @groups = Group.all
    render 'index'
  end
  def kick
    @user = User.find(params[:user_id])
    @group = Group.find(params[:id])
    #Add code to remove from all tasks and subtasks too
    if @group.members.include? @user
      @group.members.delete(@user)
    end
    if @group.mods.include? @user
      @group.mods.delete(@user)
    end
  end
  def join
    @group = Group.find(params[:id])
    @grequests = Grequest.where("user_id = ? AND group_id = ?", current_user.id, @group.id)
    puts "-----------------"
    puts @grequests
    puts @grequest.nil?
    if @group and !@group.members.include? current_user
      if !@grequests.any?
        @grequest = Grequest.new(user_id: current_user.id,
                            group_id: @group.id)
        if @grequest.save
          redirect_to group_path(@group)
        else
          flash["error"] = "Could not create a request"
          redirect_to request.referer
        end
      else
        flash["error"] = "You have already requested to join"
        redirect_to request.referer
      end
    else
      flash["error"] = "Already in Group"
      redirect_to request.referer
    end
  end
  def accept
    @grequest = Grequest.find(params[:grequest_id])
    @grequest.group.members << @grequest.user
    puts @grequest.group.id
    puts @grequest.group.members
    puts @grequest.user.groups
    @grequest.delete
    redirect_to request.referer
  end
  def decline
    @grequest = Grequest.find(params[:grequest_id])
    @grequest.delete
    redirect_to request.referer
  end
end

app/views/groups/_group.html.erb
<div class="partial">
  <a href="/groups/<%= group.id %>" class="hidden-link">
    <h4> <%= group.name %> </h4>
    <div class="details">
      <label>Members: <%= group.members.length %></label>
    </div>
  </a>
</div>

app/views/groups/index.html.erb
<h1> Groups </h1>
<a class="btn btn-primary alignright" href="/groups/new">New Group</a>
<div>
  <%= render @groups %>
</div>

app/views/groups/new.html.erb
<div class = "center" id = "signin">

  <%= form_for(@group) do |g| %>
    <div class = "field">
    
      <%= g.text_field :name, :placeholder => "Insert Name Here"%>

      <br>


      <%= g.submit "Create Group", class: "btn btn-large btn-primary" %></div>

    <% end %>
</div>

</body>

app/views/groups/show.html.erb
<div class="container">
<h1> <%= @group.name %>
</h1>
<% if !current_user.groups.include? @group %>
  <% if Grequest.find_by_user_id_and_group_id(current_user.id, @group.id) %>
    <%= link_to '#', class: "btn disabled btn-warning" do %>
      <i class="icon-exclamation-sign icon-white"></i>
      Requested
    <% end %>
  <% else %>
    <%= link_to "Join", join_group_path(@group) , class: "btn" %>
  <% end %>
<% else %>
  <%= link_to '#', class: "btn disabled btn-success" do %>
    <i class="icon-ok icon-white"></i>
    Member
  <% end %>
<% end %>
  
<div class="tabbable">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#project-tab" data-toggle="tab">Projects</a></li>
    <li ><a href="#feed-tab" data-toggle="tab">Feed</a></li>
    <li ><a href="#member-tab" data-toggle="tab">Members</a></li>
    <% if @group.mods.include? current_user %>
      <li ><a href="#join-tab" data-toggle="tab">Requests to Join</a></li>
    <% end %>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="project-tab">
      
      <%= render @group.projects %>
    </div>
    <div class="tab-pane" id="feed-tab">
    </div>
    <div class="tab-pane" id="member-tab">
      <%= render @group.members %>
    </div>
    <div class="tab-pane" id="join-tab">
         <%= render @group.grequests %>  
    </div>
  </div>
</div>
  
</div>