config/routes.rb
Scrum::Application.routes.draw do
  resources :users
  resources :tasks do
    member do
      get "join"
      get "kick"
      get "trequests"
      match "/accept/:trequest_id", to: "tasks#accept"
      match "/decline/:trequest_id", to: "tasks#decline"
    end
    collection do
      get 'browse'
      get "addtask"
    end
  end
  resources :projects do
    member do
      get "join"
      get "kick"
      get "prequests"
      match "/accept/:prequest_id", to: "projects#accept"
      match "/decline/:prequest_id", to: "projects#decline"
    end
    collection do
      get 'browse'
      get "addtask"
    end
  end

  resources :groups do
    member do
      get "join"
      get "kick"
      get "grequests"
      match "/accept/:grequest_id", to: "groups#accept"
      match "/decline/:grequest_id", to: "groups#decline"
    end
    collection do
      get 'browse'
    end
  end
  resources :sessions, only: :create

  match "/",          to: "application#home", :as => :home
  match "/signup",    to: "users#new"
  match "/signin",    to: "sessions#new"
  match "/signout",    to: "sessions#destroy"

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :name, :group_id, :user_id
  has_and_belongs_to_many :mods, :class_name => 'User', :join_table => :mods_projects
  has_and_belongs_to_many :members, :class_name => 'User', :join_table => :members_projects
  has_many :tasks
  has_and_belongs_to_many :languages
  belongs_to :group
  has_many :prequests

  validate :user_has_group;
  validates :description, presence: true;
  validates :name, presence:true;

  def user_has_group
    if mods.first.groups.find(group_id).nil?
      errors.add(:group_id, "must belong to you")
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @user = current_user
    @project = Project.new
  end
  def create
    @project = Project.new(params[:project])
    @project.mods << current_user
    @project.members << current_user
    
    if @project.save
      redirect_to "/projects"
    else
      render 'new'
    end
  end
  def index
    @projects = current_user.projects
  end
  def browse
    @projects = []
    @groups = current_user.groups
    @groups.each do |g|
      g.projects.each do |p|
        if !@projects.include? p
          @projects.push p
        end
      end
    end
    render 'index'
  end
  def show
    @project = Project.find(params[:id])
    @users = @project.members
    @mods = @project.mods
    if !@project
      redirect_to "/projects"
    end
  end
  def destroy
    @project = Project.find(params[:id])
    @project.tasks.each do |t|
      t.destroy
    end
    @project.destroy
    redirect_to request.referer
  end
  def addtask
    @task = Task.new()
    @task.description = params[:description]
    @task.project_id = params[:project_id]
    @task.group_id = Project.find(params[:project_id]).group_id
    @task.users << current_user
    @task.save
    render @task
  end
  def kick
    @user = User.find(params[:user_id])
    @project = Project.find(params[:id])
    #Add code to remove from all tasks and subtasks too
    if @project.members.include? @user
      @project.members.delete(@user)
    end
    if @project.mods.include? @user
      @project.mods.delete(@user)
    end
  end
  def join
    @project = Project.find(params[:id])
    @prequests = @project.prequests.where("user_id = ?", current_user.id)
    if @project and current_user.groups.include? @project.group
      if !@prequests.any?
        @prequest = Prequest.new(user_id: current_user.id,
                            project_id: @project.id)
        if @prequest.save
          redirect_to project_path(@project)
        else
          flash["error"] = "Could not create a request"
          redirect_to request.referer
        end
      else
        flash["error"] = "You have already requested to join"
        redirect_to request.referer
      end
    else
      flash["error"] = "Not a valid project"
      redirect_to request.referer
    end
  end
  def accept
    @prequest = Prequest.find(params[:prequest_id])
    @prequest.project.members << @prequest.user
    @prequest.delete
    redirect_to request.referer
  end
  def decline
    @prequest = Prequest.find(params[:prequest_id])
    @prequest.delete
    redirect_to request.referer
  end
end

app/views/projects/_project.html.erb
<link rel="stylesheet" type="text/css" href="/assets/partials.css">
<div class="partial">
  <a href="/projects/<%= project.id %>" class="hidden-link">
    <h2> <%= project.name %> </h2>
    <div>
      <%= project.description %>
    </div>
    <% if project.mods.include? current_user %>
      <%= button_to "Delete",project, method: "delete", class: "btn btn-danger" %>
    <% end %>
    <% if current_user.groups.include? project.group and !project.members.include? current_user %>
      <%= link_to "Join", join_project_path(project) , class: "btn" %>
    <% end %>
    <br>
  </a>
</div>

app/views/projects/index.html.erb
<%= render @projects %>

app/views/projects/new.html.erb
<%= form_for(@project) do |p| %>
  <%= p.text_field :name, :placeholder => "Project Name" %>
  <br>
  <%= p.text_area :description, :placeholder => "Summarize your project", class: "description" %>
  <br>
  <%= p.collection_select(:group_id, @hgroups, :id, :name) %>
  <%= p.submit "Create Project", class: "btn btn-primary" %>
<% end %>

app/views/projects/show.html.erb
<div class="wrapper">
  <div class ="alignleft title">
<h1> <%= @project.name %>
</h1>
<h5>Project Description</h5>
<%= @project.description %>
</div>
<div class="alignright">
<h5>Group</h5>
<%= render @project.group %>

<% if current_user.groups.include? @project.group and !@project.members.include? current_user %>
  <% if Prequest.find_by_user_id_and_project_id(current_user.id, @project.id) %>
    <%= link_to '#', class: "btn disabled btn-warning" do %>
      <i class="icon-exclamation-sign icon-white"></i>
      Requested
    <% end %>
  <% else %>
    <%= link_to 'Join', join_project_path(@project), class: "btn btn-primary" %>
  <% end %>
<% else %>
  <%= link_to '#', class: "btn disabled btn-success" do %>
    <i class="icon-ok icon-white"></i>
    Member
  <% end %>
<% end %>

<% if @project.mods.include? current_user %>
  <%= button_to "Delete",@project, method: "delete", class: "btn btn-danger" %>
<% end %>
</div>
</div>
<div class="tabbable">
  <ul class="nav nav-tabs">
    <li class="active"><a href="#task-tab" data-toggle="tab">Tasks</a></li>
    <li ><a href="#feed-tab" data-toggle="tab">Feed</a></li>
    <li><a href="#member-tab" data-toggle="tab"> Members</a></li>
    <% if @project.mods.include? current_user %>
      <li ><a href="#join-tab" data-toggle="tab">Requests to Join</a></li>
    <% end %>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="task-tab">
            <a href="#newTaskModal" class="accordion-toggle btn btn-success" data-toggle="collapse">New Task</a>
   
          <%= render "/tasks/new" %>
      <%= render @project.tasks %>
    </div>
    <div class="tab-pane" id="feed-tab">
    </div>
    <div class="tab-pane" id="member-tab">
      <%= render @project.members %>
    </div>
    <div class="tab-pane" id="join-tab">
         <%= render @project.prequests %>  
    </div>
  </div>
</div>