config/routes.rb
Scrum::Application.routes.draw do
  resources :users
  resources :tasks do
    member do
      get "join"
      get "kick"
      get "trequests"
      match "/accept/:trequest_id", to: "tasks#accept"
      match "/decline/:trequest_id", to: "tasks#decline"
    end
    collection do
      get 'browse'
      get "addtask"
    end
  end
  resources :projects do
    member do
      get "join"
      get "kick"
      get "prequests"
      match "/accept/:prequest_id", to: "projects#accept"
      match "/decline/:prequest_id", to: "projects#decline"
    end
    collection do
      get 'browse'
      get "addtask"
    end
  end

  resources :groups do
    member do
      get "join"
      get "kick"
      get "grequests"
      match "/accept/:grequest_id", to: "groups#accept"
      match "/decline/:grequest_id", to: "groups#decline"
    end
    collection do
      get 'browse'
    end
  end
  resources :sessions, only: :create

  match "/",          to: "application#home", :as => :home
  match "/signup",    to: "users#new"
  match "/signin",    to: "sessions#new"
  match "/signout",    to: "sessions#destroy"

  

end

app/views/layouts/_header.html.erb
<div class="header-container navbar navbar-inner">    
<span class = " h1 alignleft hpad">
  <%= link_to "Scrum", home_path, class: "brand" %>
</span>
<div class="nav-collapse in collapse alignright" id="main-menu" style="height: auto;">
  <ul class="nav" id="main-menu-left">
  <% if signed_in? %>
    <li> 
      <a class="hover-dropdown" href="/projects">Projects</a>
      <ul class="hover-dropdown-menu">
        <% @hprojects.each do |p| %>
          <li> <%= link_to p.name, project_path(p) %></li>
        <% end %>
        <li class="divider"></li>
        <li><%= link_to "Browse", browse_projects_path %></li>
        <li><a href="/projects/new">New Project</a></li>
      </ul>
    </li>
    <li> 
      <a class="hover-dropdown" href="/tasks">Tasks</a>
      <ul class="hover-dropdown-menu">
        <% @htasks.each do |t| %>
          <li> <%= link_to t.description, task_path(t) %></li>
        <% end %>
        <li class="divider"></li>
        <li><%= link_to "Browse", browse_tasks_path %></li>
        <li><a href="/tasks/new">New Task</a></li>
      </ul>
    </li>
    <li>
      <a class="hover-dropdown" href="/groups">Groups</a>
      <ul class="hover-dropdown-menu">
        <% @hgroups.each do |g| %>
          <li> <%= link_to g.name, group_path(g) %></li>
        <% end %>
        <li class="divider"></li>
        <li><%= link_to "Browse", browse_groups_path %></li>
        <li><%= link_to "New Group", new_group_path %></li>
      </ul>
    </li>
    <li>
     <%= link_to "Users", users_path, class: "hover-dropdown" %>  
      <ul class="hover-dropdown-menu">
        <li>
          <%= link_to "My Profile", user_path(current_user)%>
        </li>
      </ul>
    </li>
    <li>
    <%= link_to "Sign out", signout_path, class: "hover-dropdown" %> 
    <li>
  <% else %>
    <li>
      <%= link_to "Sign in", signin_path%>
    </li> 
  <% end %>
</ul>
</div>
</div>

app/views/layouts/_sidenav.html.erb
<script>
  $(document).ready(function(){
    $('#showSideNavButton').click(function() {
      $(".side-nav div").toggleClass( "active" )
    });
  });
</script>
<button class="btn" id="showSideNavButton"> Show</button>
<div class="side-nav">
  <div class="inner-side-nav">
    <ul class="nav nav-list">
      <% @hgroups.each do |g| %>
        <li>
            <div class="accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" href="#plist<%= g.id %>">
                <%= g.name %>
             </a>
           </div>
           <div id="plist<%= g.id %>" class="accordion-body collapse">
             <ul>
               <% g.projects.each do |p| %>
                 <li>
                      <div class="accordion-heading">
                        <a class="accordion-toggle" title="<%= project_url(p) %>" data-toggle="collapse" href="#tlist<%= g.id %>-<%= p.id %>">
                          <%= p.name %>
                       </a>
                     </div>
                     <div id="tlist<%= g.id %>-<%= p.id %>" class="accordion-body collapse">
                       <ul>
                         <% p.tasks.each do |t| %>
                           <li><a><%= t.description %></a></li>
                         <% end %>
                       </ul>
                     </div>
                </li>
               <% end %>
             </ul>
           </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scrum</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link rel="stylesheet" type="text/css" href="/assets/partials.css">
  <%= javascript_include_tag "application" %>
  <script src="/assets/modal.js" type="text/javascript"></script>
  <script type="text/javascript" src="/assets/jquery.jOrgChart.js"></script>
  <link rel="stylesheet" href="css/jquery.jOrgChart.css"/>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
    var ssInterval;
    $(document).ready(function(){
        ssInterval = window.setTimeout(showPonies, 20000);
        $(document).mousemove(function() {
          window.clearTimeout(ssInterval);
          ssInterval = window.setTimeout(showPonies, 20000);
        });
        //$('#org').jOrgChart();
      });
function showPonies() {
   window.clearTimeout(ssInterval);
}
  </script>
</head>
<body>
<header>
<%= render 'layouts/header' %>
</header>
<% if signed_in? %>
  <%= render 'layouts/sidenav' %>
<% end %>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<div class="content">
  <%= yield %>
</div>
</body>
</html>